/*
 * Language: Gmsh Scripting Language
 * Author: Tcyla <tcyla.dev@gmail.com>
 * Category: scientific
 * Description: Scripting language for Gmsh 
 * Website: https://gmsh.info/doc/texinfo/gmsh.html
 */


export default function (hljs) {
  const RESERVED_WORDS = [
    "Macro",
    "EndMacro",
    "Return",
    "Call",
    "For",
    "In",
    "EndFor",
    "If",
    "ElseIf",
    "Else",
    "EndIf",
  ];
  const BUILT_INS = [
    "Acos",
    "Asin",
    "Atan",
    "Atan2",
    "Ceil",
    "Cos",
    "Cosh",
    "Exp",
    "Fabs",
    "Fmod",
    "Floor",
    "Hypot",
    "Log",
    "Log10",
    "Max",
    "Min",
    "Modulo",
    "Round",
    "Sqrt",
    "Sin",
    "Sinh",
    "Tan",
    "Tanh",
    "Abort",
    "Exit",
    "CreateDir",
    "Printf",
    "Warning",
    "Error",
    "Merge",
    "ShapeFromFile",
    "Draw",
    "SplitCurentWindowHorizontal",
    "SplitCurentWindowVertical",
    "SetCurrentWindow",
    "UnsplitWindow",
    "SetChanged",
    "BoundingBox",
    "Delete",
    "Print",
    "Sleep",
    "SystemCall",
    "NonBlockingSystemCall",
    "OnelabRun",
    "SetName",
    "SetFactory",
    "SyncModel",
    "NewModel",
    "Include",
  ];
  const LITERALS = [
    "Pi",
    "GMSH_MAJOR_VERSION",
    "GMSH_MINOR_VERSION",
    "GMSH_PATCH_VERSION",
    "MPI_Size",
    "MPI_Rank",
    "Cpu",
    "Memory",
    "TotalMemory",
    "newp",
    "newc",
    "news",
    "newv",
    "newcl",
    "newsl",
    "newll",
    "newl",
    "newreg",
  ];
  const TYPES = [
    "Physical",
    "Point",
    "Point",
    "Line",
    "Bezier",
    "BSpline",
    "Circle",
    "Ellipse",
    "Compound",
    "Spline",
    "Spline",
    "Curve",
    "Loop",
    "Wire",
    "Plane",
    "Surface",
    "Disk",
    "Rectangle",
    "Volume",
    "Sphere",
    "Cylinder",
    "Torus",
    "Cone",
    "Wedge",
    "Ruled",
    "ThruSections",
  ];
  return {
    aliases: ['geo', 'gmsh'],
    case_insensitive: false,
    keywords: {
      keyword: RESERVED_WORDS,
      built_in: BUILT_INS,
      literal: LITERALS,
      type: TYPES,
    },
    contains: [
      hljs.C_NUMBER_MODE,
      hljs.QUOTE_STRING_MODE,
      hljs.C_BLOCK_COMMENT_MODE,
      hljs.C_LINE_COMMENT_MODE,
    ]
  };
}
